language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files
        - .phpunit

matrix:
    include:
        - php: 7.1
        - php: 7.2

before_script:
    - travis_retry composer install

script:
    - ./vendor/bin/simple-phpunit
